services:
  fide_nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8010:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
    depends_on:
      - fide_postgres
      - fide_php

  fide_php:
    build:
      context: .
      dockerfile: dockerfiles/php.Dockerfile
    volumes:
      - ./src:/var/www/laravel

  fide_postgres:
    image: postgres:15
    restart: always
    env_file:
      - env/postgres.env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
