name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Start Containers
        run: |
          docker compose down -v --remove-orphans || true
          docker compose up --build --force-recreate -d 
      
      - name: Verify Laravel Directory fide_php
        run: |
          docker exec fide_php ls -lah /var/www/
          docker exec fide_php ls -lah /var/www/laravel      

      - name: Verify Laravel Directory fide_nginx
        run: |
          docker exec fide_nginx ls -lah /var/www/
          docker exec fide_nginx ls -lah /var/www/laravel              

